#!/bin/sh
### BEGIN INIT INFO
# Provides:          hwclock
# Required-Start:
# Required-Stop:
# Default-Start:     S 1 2 3 4 5
# Default-Stop:      0 6
# Short-Description: Hardware clock sync
# Description:       Syncronizes the system clock to the hardware clock
#                    at shutdown and the hardware clock to the system
#                    clock at bootup
### END INIT INFO
# -*- coding: utf-8 -*-
# Debian init.d script for hwclock
# Copyright Nokia Corporation 2008

case "$1" in
  start)
    if test -x "/sbin/hwclock"; then
      echo -n 'Synching hardware clock to system time ... '
      /sbin/hwclock -s
      if test "x$?" = "x0"; then
        echo "OK"
      else
        echo "FAILED"
      fi
    fi
  ;;
  stop)
    if test -x "/sbin/hwclock"; then
      echo -n 'Synching system time to hardware clock ... '
      /sbin/hwclock -w
      if test "x$?" = "x0"; then
        echo "OK"
      else
        echo "FAILED"
      fi
    fi
  ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop}" >&2
    exit 2
  ;;
esac
