#! /bin/sh
### BEGIN INIT INFO
# Provides:		zzzremove-first-boot-flag
# Required-Start:	$all
# Required-Stop:
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 2 3 4 5 6
# Short-Description:	Remove first-boot-flag.
# Description:		Removes /tmp/first-boot-flag-tmp, concluding
#			the first boot.
### END INIT INFO
#
# Init startup kludge to notify, via D-Bus,
# that a runlevel has run all the init-scripts
#
# Copyright © 2007 Nokia Corporation.  All rights reserved.
#
# @author David Weinehall <david.weinehall@nokia.com>

FIRST_BOOT_FLAG_TMP=/tmp/first-boot-flag-tmp
INITFILE=/etc/init.d/zzzremove-first-boot-flag

case "$1" in
start|restart|force-reload)
	printf "Removing $FIRST_BOOT_FLAG_TMP"
	if test -e $FIRST_BOOT_FLAG_TMP; then
	  rm -f $FIRST_BOOT_FLAG_TMP
	fi
	printf ".\n"
	;;

stop)
	;;

status)
	;;

*)
	printf "Usage: $INITFILE {start|stop|restart|force-reload}\n" >&2
	exit 1
	;;
esac

exit 0
