#!/sbin/openrc-run

# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

description="This start the dbus user session that maemo services depend on"
name="dbus user session"

depend() {
    need dbus dsme
}

start() {
    ebegin "Starting dbus user session"
    su - user /etc/osso-af-init/real-af-dbus start
}

stop() {
    eend "Stopping dbus user session"
    su - user /etc/osso-af-init/real-af-dbus stop
}
