#!/bin/sh

TMP_DIR=/var/tmp

rm -f /etc/osso-af-init/gconf-dir
ln -s /var/lib/gconf /etc/osso-af-init/gconf-dir

update-rc.d dbus-user defaults > /dev/null
update-rc.d af-services defaults > /dev/null
#update-rc.d af-startup defaults > /dev/null
#update-rc.d af-base-apps defaults > /dev/null
#update-rc.d hwclock start 01 S 1 2 3 4 5 . stop 02 0 1 2 3 4 5 6 . > /dev/null
update-rc.d zzzremove-first-boot-flag defaults > /dev/null

# evil hack to ensure execute permissions
chmod +x /etc/osso-af-init/get-devlock.sh

# AF environment is included to every shell
line="source /etc/osso-af-init/af-defines.sh"
if ! grep -F -q "$line" /etc/profile; then
  echo "+$line"
  echo "$line" >> /etc/profile
fi

#DEBHELPER#
