#!/bin/sh

cat_default_locale_file() # No args
{
cat <<'EOF'
#!/bin/sh

if [ -f /usr/share/osso-af-init/locale ]; then
  source /usr/share/osso-af-init/locale
else
  unset LC_ALL
  unset LANGUAGE
  export LANG=en_GB
  export LC_MESSAGES=en_GB
fi
EOF
}

TGT=''
if [ -e /targets/links/scratchbox.config ] ; then
        . /targets/links/scratchbox.config
        TGT=$SBOX_TARGET_DIR
fi

USER=user
GROUP=users
HOME="$TGT/home/$USER"
LOCALE_TMP_FILE=/var/tmp/osso-af-init.locale.tmp
LOCALE_DIR=/usr/share/osso-af-init
LOCALE_FILE=/etc/osso-af-init/locale
LOCALE_ORIG_FILE=$LOCALE_DIR/locale.orig

if test "x$1" = "xinstall"; then
  # walk the user through initial configuration wizards

  if ! test -d $HOME; then
    mkdir -p $HOME
    chmod 750 $HOME
    chown $USER:$GROUP $HOME
  fi

  touch $HOME/first-boot-flag
  chown $USER:$GROUP $HOME/first-boot-flag
fi

if test -f $LOCALE_FILE; then
  cp -af $LOCALE_FILE $LOCALE_TMP_FILE
else
  cat_default_locale_file > $LOCALE_TMP_FILE
fi

mkdir -p $LOCALE_DIR
cat_default_locale_file > $LOCALE_ORIG_FILE
