#!/bin/sh

cat_default_locale_file() # No args
{
cat <<'EOF'
#!/bin/sh

if [ -f /usr/share/osso-af-init/locale ]; then
  source /usr/share/osso-af-init/locale
else
  unset LC_ALL
  unset LANGUAGE
  export LANG=en_GB
  export LC_MESSAGES=en_GB
fi
EOF
}

TGT=''
if [ -e /targets/links/scratchbox.config ] ; then
        . /targets/links/scratchbox.config
        TGT=$SBOX_TARGET_DIR
fi

USER=user
GROUP=users
HOME="$TGT/home/$USER"
TMP_DIR=/var/tmp
LOCALE_TMP_FILE=$TMP_DIR/osso-af-init.locale.tmp
LOCALE_DIR=/usr/share/osso-af-init
LOCALE_FILE=/etc/osso-af-init/locale
LOCALE_ORIG_FILE=$LOCALE_DIR/locale.orig

if test "x$1" = "xinstall"; then
  # walk the user through initial configuration wizards

  if ! test -d $HOME; then
    mkdir -p $HOME
    chmod 750 $HOME
    chown $USER:$GROUP $HOME
  fi

  touch $HOME/first-boot-flag
  chown $USER:$GROUP $HOME/first-boot-flag
fi

mkdir -p $TMP_DIR
chmod 1777 $TMP_DIR

if test -f $LOCALE_FILE; then
  echo "osso-af-startup: preinst: Backing up existing locale file to $LOCALE_TMP_FILE"
  cp -af $LOCALE_FILE $LOCALE_TMP_FILE
else
  echo "osso-af-startup: preinst: Creating default locale file in $LOCALE_TMP_FILE"
  cat_default_locale_file > $LOCALE_TMP_FILE
fi

echo "osso-af-startup: preinst: Creating directory $LOCALE_DIR"
mkdir -p $LOCALE_DIR
echo "osso-af-startup: preinst: Generating default locale-orig file $LOCALE_ORIG_FILE"
cat_default_locale_file > $LOCALE_ORIG_FILE
